protected/modules/dryadmin/models/User.php
<?php

/**
 * This is the model class for table "users".
 *
 * The followings are the available columns in table 'users':
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $login
 * @property string $pass
 * @property integer $active
 * @property integer $deleted
 * @property string $created
 */
class User extends CActiveRecord
{
	public $login;
	public $pass;
	
	
	/**
	 * Returns the static model of the specified AR class.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, email, login, pass', 'required'),
			array('active, deleted', 'numerical', 'integerOnly'=>true),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, email, login, pass, active, deleted, created', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Имя',
			'email' => 'Email',
			'login' => 'Логин',
			'pass' => 'Хеш пароля',
			'active' => 'Активный',
			'deleted' => 'Невидимый',
			'created' => 'Дата регистрации',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('login',$this->login,true);
		$criteria->compare('pass',$this->pass,true);
		$criteria->compare('active',$this->active);
		$criteria->compare('deleted',$this->deleted);
		$criteria->compare('created',$this->created,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/modules/dryadmin/controllers/DefaultController.php
<?php

class DefaultController extends Controller
{
	public $layout = 'twocolumn';
	public function actionIndex()
	{
		$this->render('index');
	}
}

protected/modules/dryadmin/controllers/FilemanagerController.php
<?php
class FilemanagerController extends Controller
{
	public $layout = '/layouts/body_filemanager';
	
	public function actionIndex()
	{
		$this->render('index');
	}
}

protected/modules/dryadmin/controllers/LoginController.php
<?php
class LoginController extends Controller
{
	public $defaultAction = 'login';
	public $layout = 'login';
	public $allowAutoLogin = true;

	public function actionLogin()
	{
		$model = new LoginForm;
		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login', array('model' => $model));
	}
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/modules/dryadmin/controllers/SectionController.php
<?php

class SectionController extends DSectionController
{
    // Идентификация меню для "Управления пользователей"
    public $menu = array();
}

protected/modules/dryadmin/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='twocolumn';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;
                $model->created = CTimestamp::formatDate('Y-m-d',time());
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'Запрашиваемый пользователь н найден.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/dryadmin/views/filemanager/index.php
<div id="finder"></div>

<script type="text/javascript">
$(document).ready(function() {
	 
	var funcNum = window.location.search.replace(/^.*CKEditorFuncNum=(\d+).*$/, "$1");
	var langCode = window.location.search.replace(/^.*langCode=([a-z]{2}).*$/, "$1");
	
	$('#finder').elfinder({
		url : '<?php echo $this->module->assetsUrl?>/elfinder/connectors/php/connector.php',
		lang : langCode,
		editorCallback : function(url) {
			window.opener.CKEDITOR.tools.callFunction(funcNum, url);
			window.close();
    	}
	});
})
</script>

protected/modules/dryadmin/views/layouts/body.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="ru" />

	<?php echo CHtml::cssFile($this->module->assetsUrl.'/jqui/css/Aristo/Aristo.css')?>
	<?php echo CHtml::cssFile($this->module->assetsUrl.'/elfinder/css/elfinder.css')?>

	<?php
		/**
		 * @var CClientScript $cs
		 */
		$cs = Yii::app()->clientScript;
		$cs->registerCoreScript('jquery');
		$cs->registerCoreScript('jquery.ui');

		$cs->registerScriptFile($this->module->assetsUrl.'/jqui/js/i18n/jquery.ui.datepicker-ru.js', CClientScript::POS_BEGIN);
		$cs->registerScriptFile($this->module->assetsUrl.'/ckeditor/ckeditor.js', CClientScript::POS_BEGIN);
		$cs->registerScriptFile($this->module->assetsUrl.'/ckeditor/adapters/jquery.js', CClientScript::POS_BEGIN);
		$cs->registerScriptFile($this->module->assetsUrl.'/elfinder/js/elfinder.min.js', CClientScript::POS_BEGIN);
		$cs->registerScriptFile($this->module->assetsUrl.'/elfinder/js/i18n/elfinder.ru.js', CClientScript::POS_BEGIN);

		$cs->registerScript('datepickerSetup', "$.datepicker.setDefaults($.datepicker.regional['ru']);", CClientScript::POS_BEGIN);
	?>

	<?php Yii::app()->clientScript->registerCssFile($this->module->assetsUrl.'/iconic/iconic.css'); ?>
	<?php Yii::app()->clientScript->registerCssFile($this->module->assetsUrl.'/admin-style.css'); ?>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
	<?php echo $content; ?>
</body>
</html>

protected/modules/dryadmin/views/layouts/body_filemanager.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="ru" />

	<?php echo CHtml::cssFile($this->module->assetsUrl.'/jqui/css/Aristo/Aristo.css')?>
	<?php echo CHtml::cssFile($this->module->assetsUrl.'/elfinder/css/elfinder.css')?>

	<?php echo CHtml::scriptFile($this->module->assetsUrl.'/jquery-1.7.min.js'); ?>
	<?php echo CHtml::scriptFile($this->module->assetsUrl.'/jqui/js/jquery-ui-1.8.16.custom.min.js'); ?>
	<?php echo CHtml::scriptFile($this->module->assetsUrl.'/jqui/js/i18n/jquery.ui.datepicker-ru.js'); ?>
	
	<?php echo CHtml::scriptFile($this->module->assetsUrl.'/elfinder/js/elfinder.min.js'); ?>
	<?php echo CHtml::scriptFile($this->module->assetsUrl.'/elfinder/js/i18n/elfinder.ru.js'); ?>
	
	<?php echo CHtml::script("$.datepicker.setDefaults($.datepicker.regional['ru']);")?>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
	<?php echo $content; ?>
</body>
</html>

protected/modules/dryadmin/views/layouts/login.php
<?php $this->beginContent('/layouts/body'); ?>
<div class="container">
	<div class="row" style="padding-top:3em;">
		<div class="span6 offset3">
			<?php echo $content; ?>
		</div>
	</div>
</div>
<?php $this->endContent();?>

protected/modules/dryadmin/views/layouts/twocolumn.php
<?php $this->beginContent('/layouts/body'); ?>
<?php
	$this->widget('bootstrap.widgets.BootNavbar', array(
		'fixed' => true,
		'fluid' => true,
		'brand' => Yii::app()->name,
		'brandUrl' => $this->createUrl('section/index', array('section' => 'page')),
		'items' => array(
			array(
				'class' => 'bootstrap.widgets.BootMenu',
				'items' => array(
					array('label' => 'Выход', 'url' => '#'),
				)
			)
		),
	));
?>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<?php
				$this->widget('bootstrap.BootMenu', array(
					'type' => 'list',
					'items' => $this->structureMenu,
				));
			?>
		</div>
		<div class="span10">
			<?php $this->widget('bootstrap.widgets.BootBreadcrumbs', array('links' => $this->breadcrumbs, 'homeLink' => FALSE)); ?>
			<?php echo $content; ?>
		</div>
	</div>
</div>
<?php $this->endContent();?>

protected/modules/dryadmin/views/login/login.php
<?php echo CHtml::beginForm('', 'post', array('class' => 'form-vertical')) ?>
	
	<div class="<?php if (isset($model->errors['login'])) echo 'error';?>">
		<?php echo CHtml::activeLabel($model, 'login'); ?>
		<div class="input">
			<?php echo CHtml::activeTextField($model, 'login', array('class' => 'xlarge')); ?>
			<span class="help-inline"><?php echo $model->getError('login');?></span>
		</div>
	</div>
	
	<div class="<?php if (isset($model->errors['password'])) echo 'error';?>">
		<?php echo CHtml::activeLabel($model, 'password'); ?>
		<div class="input">
			<?php echo CHtml::activePasswordField($model, 'password', array('class' => 'xlarge')); ?>
			<span class="help-inline"><?php echo $model->getError('password');?></span>
		</div>
	</div>
	<div class="row rememberMe">
		<?php echo CHtml::activeCheckBox($model,'rememberMe'); ?>
	</div>
	<div class="actions">
		<?php echo CHtml::submitButton('Войти'); ?>
	</div>
	
	
<?php echo CHtml::endForm(); ?>

protected/modules/dryadmin/views/section/add.php
<div class="row">
	<div class="span12">
	<?php
		$this->widget('DForm', $_data_);
	?>
	</div>
</div>

protected/modules/dryadmin/views/section/index.php
<?php
/**
 * @var DSectionController $this
 */
?>

<?php
	$this->widget('bootstrap.widgets.BootGridView', array(
		'dataProvider' => $recordsData,
		'template' => '{items}',
		'itemsCssClass'=>'table table-striped',
		'columns' => $this->getGridColumns(),
	));
?>

<?php
	$this->widget('bootstrap.widgets.BootButton', array(
		'fn'    => 'link',
		'label' => 'Добавить',
		'url'   => $this->createUrl('add', $this->actionParams),
	));
?>
	

protected/modules/dryadmin/views/section/update.php
<div class="row">
	<div class="span12">
	<?php
		$this->widget('DForm', array(
			'model' => $model,
			'record' => $record));
	?>
	</div>
</div>